language: c

compiler:
  - gcc

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - libjson0-dev
      - intltool
      - gobject-introspection

script:
    - ./autogen.sh
    - ./configure
    - make
    - make clean
    - make distcheck
    - make maintainer-clean
